### ISSUE TITLE
After add RoutingAutoBundle - Notice: Undefined offset: 0 

### ISSUE THREAD

**Issue by Micchaleq** [symfony-cmf/routing-auto-bundle#154] opened 2015-02-27 21:06 UTC
Hi, all

I have next problem with cmf bundle. I created my own cms on routing bundle and everything work fine. I want to add blog to my cms so I installed RoutingAutoBundle and after that ( without any configuration ). I just adding it to AppKernel.

When I run homepage I get an error : Notice: Undefined offset: 0 (RouteCompiler.php line 165 )

When I try to run some page /about-us I get this same error but it is linked with
{{ path(cmf_find('/cms/routes')) }}
{{ knp_menu_render('main-menu'}) }}

I have to add that routingAutoBundle work fine, but my menu and old routes don't.

Any one can help me?

**Comment by WouterJ** [comment] 2015-02-27 23:43
Thank you for reporting the error, @Micchaleq!

The error is from Symfony source code (https://github.com/symfony/Routing/blob/master/RouteCompiler.php#L165). That class is used to compile routes to the cache. For some reason, it can't correctly parse the URL you configured.

Can you please show your RoutingAutoBundle mapping configuration?

**Comment by Micchaleq** [comment] 2015-03-01 11:51
Hi, thank you for information. I solved this problem. I changed my route_basepath in cmf_routing from routes to route and now it works fine. I haven't got any configuration for autoroutebundle

**Comment by WouterJ** [comment] 2015-03-01 12:12
Hmm, in that case, I'm going to reopen this issue as a bug. Imo, things should always work out of the box and it seems like this bundle doesn't do that at the moment. After all, a raw PHP error caused by a third party library never is great.

I'll digg into this a bit more

**Comment by dbu** [comment] 2017-08-10 10:56
i think this is by now obsolete, closing

**Closed by dbu** 2017-08-10 10:56 UTC
Labels: bug
